#!/bin/sh 

LLIB=/usr/local/lib/menjar

declare -a dirs
cache="${XDG_DATA_HOME:-${HOME}/.local/share}/menjar.dat"
dirs=("/usr/local/share/applications" "/usr/share/applications")
keep=true

while [[ $# -ne 0 ]]
do
	case $1 in
		-f)	keep=false         ;;
		-t)	term="$2"  ; shift ;;
		-d)	dirs+="$2" ; shift ;;
		 *)	echo "Unknown option: $1"
			exit 1             ;;
	esac
	shift
done


for d in "${dirs[@]}"
do
	if [[ "$d" -nt "$cache" ]]
	then
		keep=false
		break
	fi
done

if $keep
then
	cat $cache
else
	find "${dirs[@]}" -type f -name \*.desktop \
		| xargs awk -f $LLIB/menjar1.awk -- term="$term" \
		| sort \
		| tee $cache
fi | awk -f $LLIB/menjar2.awk

